# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true
gems: [jekyll-paginate]

# Setup
title:               Disgruntled Biochemist
tagline:             'Teaching fellow-ing along'
description:         ''
url:                 http://cistron.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Michael Baron
  url:               https://twitter.com/photo_receptor
  email:             michael.baron@ucl.ac.uk

# Custom vars
version:             1.0.0
