# Permalinks
permalink:           pretty

# Setup
title:               'Delightfully unprofessorial'
description:         "Stuff 'n things' by Dr. Michael Baron."
url:                 http://cistron.github.io
baseurl:             ''

# About/contact
author:
  name:              Michael Baron
  url:               http://cistron.github.io
  email:             m.baron@gmx.net

include: ["_splats"]