# Permalinks
permalink:           pretty

# Setup
title:               'Delightfully unprofessorial'
description:         'Teaching materials and ruminations by Dr. Michael Baron.'
url:                 http://cistron.github.io
baseurl:             ''

# About/contact
author:
  name:              Michael Baron
  url:               https://iris.ucl.ac.uk/iris/browse/profile?upi=MBARO00
  email:             michael.baron@ucl.ac.uk

include: ["_splats"]