# Permalinks
permalink:           pretty

# Setup
title:               'The roots of the tree of knowledge are bitter'
tagline:             'but the fruits are sweet'
description:         'Teaching materials and ruminations by Dr. Michael Baron.'
url:                 http://cistron.github.io
baseurl:             ''

# About/contact
author:
  name:              Michael Baron
  url:               https://twitter.com/photo_receptor
  email:             michael.baron@ucl.ac.uk

include: ["_splats"]